language: python

python:
  - 3.7

install:
  - pip install -r ./ebdjango/requirements.txt

before_script:
  - python3 ./ebdjango/manage.py migrate


script:
  - black --check .
  - flake8 .
  - coverage run ebdjango/manage.py test 

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIARMWT2YKIQ22S5GZQ"
  secret_access_key: "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"
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-096007275153
  on:
    branch: CI
      


after_script:
  - COVERALLS_REPO_TOKEN=ZrSRNiGR0JX1DxOYgG9QGur4St5YeQAIt coveralls  
