language: python

python:
  - 3.7

install:
  - pip install -r ./ebdjango/requirements.txt

before_script:
  - python3 ./ebdjango/manage.py migrate


script:
  - black --check .
  - flake8 .
  - coverage run ebdjango/manage.py test 

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAT4YP6OQK6ZA2JJNX"
  secret_access_key: "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"
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-267932038165
  on:
    branch: CI
      


after_script:
  - COVERALLS_REPO_TOKEN=ZrSRNiGR0JX1DxOYgG9QGur4St5YeQAIt coveralls  
